[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "codeberg.org/yelosan/hugo-feeds"

[[imports]]
  path = "codeberg.org/yelosan/hugo-shortcodes"

[[imports]]
  path = "codeberg.org/yelosan/hugo-semantic-web"

[[imports]]
  path = "gitlab.com/youronlyone/images"
  # BGN: /yuki/ images
    [[imports.mounts]]
      source = "yuki"
      target = "assets/images"
  # END: /yuki/ images

  # BGN: /snoworld/ images
    [[imports.mounts]]
      source = "snoworld"
      target = "assets/images"
  # END: /snoworld/ images

  # BGN: /love/ images
    [[imports.mounts]]
      source = "love"
      target = "assets/images"
  # END: /love/ images

  # BGN: /way/ images
    [[imports.mounts]]
      source = "way"
      target = "assets/images"
  # END: /way/ images

  # BGN: /techmagus/ images
    [[imports.mounts]]
      source = "techmagus"
      target = "assets/images"
  # END: /techmagus/ images

[[imports]]
  path = "codeberg.org/youronlyone/content"
  # BGN: /yuki/ content
    #[[imports.mounts]]
    #  source = "yuki/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "yuki/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "yuki/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "yuki/ko"
      target = "content"
      lang = "ko"
  # END: /yuki/ content

  # BGN: /snoworld/ content
    #[[imports.mounts]]
    #  source = "snoworld/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "snoworld/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "snoworld/ko"
      target = "content"
      lang = "ko"
  # END: /snoworld/ content

  # BGN: /love/ content
    #[[imports.mounts]]
    #  source = "love/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "love/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "love/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "love/ko"
      target = "content"
      lang = "ko"
  # END: /love/ content

  # BGN: /way/ content
    #[[imports.mounts]]
    #  source = "way/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "way/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "way/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "way/ko"
      target = "content"
      lang = "ko"
  # END: /way/ content

  # BGN: /techmagus/ content
    #[[imports.mounts]]
    #  source = "techmagus/en-ph"
    #  target = "content"
    #  lang = "en"
    [[imports.mounts]]
      source = "techmagus/en-ph"
      target = "content"
      lang = "en-ph"
    [[imports.mounts]]
      source = "techmagus/ja"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "techmagus/ko"
      target = "content"
      lang = "ko"
  # END: /techmagus/ content

  # BGN: /yuki/ fill gaps content
    [[imports.mounts]]
      source = "yuki/en-ph"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "yuki/en-ph"
      target = "content"
      lang = "ko"
  # END: /yuki/ fill gaps content

  # BGN: /snoworld/ fill gaps content
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "snoworld/en-ph"
      target = "content"
      lang = "ko"
  # END: /snoworld/ fill gaps content

  # BGN: /love/ fill gaps content
    [[imports.mounts]]
      source = "love/en-ph"
      target = "content"
      lang = "ja"
    [[imports.mounts]]
      source = "love/en-ph"
      target = "content"
      lang = "ko"
  # END: /love/ fill gaps content

  # BGN: /way/ fill gaps content
    #[[imports.mounts]]
    #  source = "way/en-ph"
    #  target = "content"
    #  lang = "ja"
    #[[imports.mounts]]
    #  source = "way/en-ph"
    #  target = "content"
    #  lang = "ko"
  # END: /way/ fill gaps content

  # BGN: /techmagus/ fill gaps content
    #[[imports.mounts]]
    #  source = "techmagus/en-ph"
    #  target = "content"
    #  lang = "ja"
    #[[imports.mounts]]
    #  source = "techmagus/en-ph"
    #  target = "content"
    #  lang = "ko"
  # END: /techmagus/ fill gaps content

[[imports]]
  path = "codeberg.org/youronlyone/defaults"

[[imports]]
  path = "github.com/techmagus/hugo-theme-dream"


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  #[[mounts]]
  #  source = "content/en-ph"
  #  target = "content"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "content/en-ph"
    target = "content"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "content/ja"
    target = "content"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "content/ko"
    target = "content"
    lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  #[[mounts]]
  #  source = "static/en-ph"
  #  target = "static"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "static/en-ph"
    target = "static"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "static/ja"
    target = "static"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "static/ko"
    target = "static"
    lang = "ko"                                         # when in multihost / multilang mode
