# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

jquerycdn = true

favicon_mstilecolor = "#2b5797"

disqusShortname = "youronlyone"

### BGN: Structured Data ###
  siteStartYear = 2021
  description = "The chronicles of ᜌᜓᜃᜒ (Yuki ・ 雪亮) / Yahuhanan Yukia Sese Cuneta."
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ", "Chronicles"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp", "https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme settings
  background = "#EBF6F7"
  backgroundImage = "https://rsc.youronly.one/img/assets/vintage-933793_1920.jpg"
  linkColor = "blue"

  # dark mode
  defaultDark = true
  backgroundDark = "#202124"
  backgroundImageDark = "https://rsc.youronly.one/img/assets/abstract-1780252_1280.png"
  darkLinkColor = "gold"
  darkNav = true
  dark404 = true

  avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"
  headerTitle = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
  motto = "If this is not the end of oblivion, then I shall live everyday as if my life were to end this very day."

  #maxTags = 5
  #footerBottomText = ""
  rss = true

  #email = ""
  #twitter = "YourOnlyONEofcl"
  facebook = "YourOnly.ONE.ofcl"
  #instagram = "YourOnly.One"
  mastodon = "https://c.im/@youronlyone" # we have our own badge
  #linkedin = "youronlyone"
  #github = ""
  #stackoverflow = ""
  #codepen = ""

  #favicon = "favicon.ico"

  highlightjs = true
  highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  hasTwitterEmbed = true
  reversePostAndAside = true
  shareInAside = false
  fixedNav = true
  collapsibleTags = true
  collapseBySummary = false
  # disableFlip = true
  # hideBackSocialLinks = true

  #[advanced]
  #  customCSS = ["css/custom.css"]
  #  customJSBefore = []
  #  customJS = []

  #[experimental]
  #  jsDate = true
  #  jsDateFormat = "yyyy年MM月dd日"
### END: Theme settings

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    isblog = true
    sameas = [
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://hashi.icu/@YourOnlyOne",
      "https://youtube.com/@YourOnlyOneOfcl",
      "https://facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
